module_name: Block Advertising
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - advertising
  - banner
  - images
  - blockadvertising
description_short: The block advertising module from thirty bees allows you to create a static advertisement image in either the right or left column of your site.
description: description.md
images:
  - image-1.png
gdpr_compliant: true
license: MIT